-- Generated by scripts/generate_studio_lettering.py; do not edit by hand.
local ADDON_NAME, NS = ...
NS.StudioLettering = { button = {}, heading = {} }
NS.StudioLettering.button["+"] = { file = "ButtonPlus", width = 14.5, height = 14.0, u = 0.90625, v = 0.875 }
NS.StudioLettering.button["Approve"] = { file = "ButtonApprove", width = 58.0, height = 17.0, u = 0.90625, v = 0.53125 }
NS.StudioLettering.button["Approved"] = { file = "ButtonApproved", width = 64.5, height = 17.0, u = 0.503906, v = 0.53125 }
NS.StudioLettering.button["Bind To This Profile"] = { file = "ButtonBindToThisProfile", width = 149.5, height = 17.0, u = 0.583984, v = 0.53125 }
NS.StudioLettering.button["Browse Builds and Imports"] = { file = "ButtonBrowseBuildsandImports", width = 189.0, height = 18.0, u = 0.738281, v = 0.5625 }
NS.StudioLettering.button["Cancel"] = { file = "ButtonCancel", width = 46.5, height = 17.0, u = 0.726562, v = 0.53125 }
NS.StudioLettering.button["Change Build"] = { file = "ButtonChangeBuild", width = 87.5, height = 17.0, u = 0.683594, v = 0.53125 }
NS.StudioLettering.button["Choose a Build"] = { file = "ButtonChooseaBuild", width = 105.0, height = 17.0, u = 0.820312, v = 0.53125 }
NS.StudioLettering.button["Classic Settings"] = { file = "ButtonClassicSettings", width = 124.0, height = 17.5, u = 0.96875, v = 0.546875 }
NS.StudioLettering.button["Clear"] = { file = "ButtonClear", width = 40.5, height = 17.0, u = 0.632812, v = 0.53125 }
NS.StudioLettering.button["Close"] = { file = "ButtonClose", width = 44.0, height = 16.5, u = 0.6875, v = 0.515625 }
NS.StudioLettering.button["Confirm"] = { file = "ButtonConfirm", width = 57.0, height = 16.5, u = 0.890625, v = 0.515625 }
NS.StudioLettering.button["Copy From Profile"] = { file = "ButtonCopyFromProfile", width = 131.0, height = 17.0, u = 0.511719, v = 0.53125 }
NS.StudioLettering.button["Create"] = { file = "ButtonCreate", width = 48.0, height = 17.0, u = 0.75, v = 0.53125 }
NS.StudioLettering.button["Delete Profile"] = { file = "ButtonDeleteProfile", width = 105.0, height = 17.0, u = 0.820312, v = 0.53125 }
NS.StudioLettering.button["Edit"] = { file = "ButtonEdit", width = 35.0, height = 17.0, u = 0.546875, v = 0.53125 }
NS.StudioLettering.button["Fit Window"] = { file = "ButtonFitWindow", width = 82.5, height = 17.5, u = 0.644531, v = 0.546875 }
NS.StudioLettering.button["New Profile"] = { file = "ButtonNewProfile", width = 87.0, height = 17.5, u = 0.679688, v = 0.546875 }
NS.StudioLettering.button["Next"] = { file = "ButtonNext", width = 36.5, height = 17.5, u = 0.570312, v = 0.546875 }
NS.StudioLettering.button["Not Set"] = { file = "ButtonNotSet", width = 60.5, height = 17.5, u = 0.945312, v = 0.546875 }
NS.StudioLettering.button["Off"] = { file = "ButtonOff", width = 35.5, height = 21.0, u = 0.554688, v = 0.65625 }
NS.StudioLettering.button["On"] = { file = "ButtonOn", width = 27.0, height = 20.0, u = 0.84375, v = 0.625 }
NS.StudioLettering.button["Open Talents"] = { file = "ButtonOpenTalents", width = 93.5, height = 17.5, u = 0.730469, v = 0.546875 }
NS.StudioLettering.button["Preview Motion"] = { file = "ButtonPreviewMotion", width = 110.0, height = 17.0, u = 0.859375, v = 0.53125 }
NS.StudioLettering.button["Previous"] = { file = "ButtonPrevious", width = 66.0, height = 17.0, u = 0.515625, v = 0.53125 }
NS.StudioLettering.button["Rename"] = { file = "ButtonRename", width = 48.0, height = 16.5, u = 0.75, v = 0.515625 }
NS.StudioLettering.button["Reset & Rebuild"] = { file = "ButtonResetRebuild", width = 110.0, height = 16.0, u = 0.859375, v = 1.0 }
NS.StudioLettering.button["Reset To Defaults"] = { file = "ButtonResetToDefaults", width = 130.5, height = 17.5, u = 0.509766, v = 0.546875 }
NS.StudioLettering.button["Spend Available Points"] = { file = "ButtonSpendAvailablePoints", width = 162.5, height = 17.5, u = 0.634766, v = 0.546875 }
NS.StudioLettering.button["Switch Profile"] = { file = "ButtonSwitchProfile", width = 110.0, height = 17.0, u = 0.859375, v = 0.53125 }
NS.StudioLettering.button["Talent Options"] = { file = "ButtonTalentOptions", width = 108.5, height = 17.5, u = 0.847656, v = 0.546875 }
NS.StudioLettering.button["Tune Motion"] = { file = "ButtonTuneMotion", width = 86.0, height = 17.0, u = 0.671875, v = 0.53125 }
NS.StudioLettering.button["Unavailable"] = { file = "ButtonUnavailable", width = 79.5, height = 17.0, u = 0.621094, v = 0.53125 }
NS.StudioLettering.button["Unbind Character"] = { file = "ButtonUnbindCharacter", width = 115.5, height = 17.0, u = 0.902344, v = 0.53125 }
NS.StudioLettering.button["Undo Respec"] = { file = "ButtonUndoRespec", width = 86.5, height = 17.0, u = 0.675781, v = 0.53125 }
NS.StudioLettering.button["X"] = { file = "ButtonX", width = 15.0, height = 16.5, u = 0.9375, v = 0.515625 }
NS.StudioLettering.button["\\"] = { file = "ButtonGrip", width = 11.5, height = 16.5, u = 0.71875, v = 0.515625 }
NS.StudioLettering.button["← Talents"] = { file = "ButtonLeftTalents", width = 80.0, height = 18.0, u = 0.625, v = 0.5625 }
NS.StudioLettering.button["↑"] = { file = "ButtonUp", width = 12.5, height = 22.0, u = 0.78125, v = 0.6875 }
NS.StudioLettering.button["↓"] = { file = "ButtonDown", width = 12.5, height = 22.0, u = 0.78125, v = 0.6875 }
NS.StudioLettering.button["−"] = { file = "ButtonMinus", width = 15.5, height = 8.0, u = 0.96875, v = 1.0 }
NS.StudioLettering.heading["Advanced"] = { file = "HeadingAdvanced", width = 78.5, height = 24.0, u = 0.613281, v = 0.75 }
NS.StudioLettering.heading["Animated Clone"] = { file = "HeadingAnimatedClone", width = 127.5, height = 24.0, u = 0.996094, v = 0.75 }
NS.StudioLettering.heading["Automation & Safety"] = { file = "HeadingAutomationSafety", width = 174.0, height = 24.0, u = 0.679688, v = 0.75 }
NS.StudioLettering.heading["BetterSBA"] = { file = "HeadingBetterSBA", width = 88.0, height = 24.0, u = 0.6875, v = 0.75 }
NS.StudioLettering.heading["Build Automation"] = { file = "HeadingBuildAutomation", width = 144.0, height = 24.0, u = 0.5625, v = 0.75 }
NS.StudioLettering.heading["Build Library"] = { file = "HeadingBuildLibrary", width = 110.5, height = 24.0, u = 0.863281, v = 0.75 }
NS.StudioLettering.heading["Burst Particles"] = { file = "HeadingBurstParticles", width = 130.0, height = 24.0, u = 0.507812, v = 0.75 }
NS.StudioLettering.heading["Button"] = { file = "HeadingButton", width = 62.0, height = 24.0, u = 0.96875, v = 0.75 }
NS.StudioLettering.heading["Button & Queue"] = { file = "HeadingButtonQueue", width = 131.5, height = 24.0, u = 0.513672, v = 0.75 }
NS.StudioLettering.heading["Button Keybind"] = { file = "HeadingButtonKeybind", width = 125.5, height = 24.0, u = 0.980469, v = 0.75 }
NS.StudioLettering.heading["Button Keybind Font"] = { file = "HeadingButtonKeybindFont", width = 168.0, height = 24.0, u = 0.65625, v = 0.75 }
NS.StudioLettering.heading["Cast Feedback"] = { file = "HeadingCastFeedback", width = 117.5, height = 23.5, u = 0.917969, v = 0.734375 }
NS.StudioLettering.heading["Choose a Build"] = { file = "HeadingChooseaBuild", width = 122.0, height = 24.0, u = 0.953125, v = 0.75 }
NS.StudioLettering.heading["Class Abilities"] = { file = "HeadingClassAbilities", width = 120.0, height = 24.0, u = 0.9375, v = 0.75 }
NS.StudioLettering.heading["Classic Animation"] = { file = "HeadingClassicAnimation", width = 147.5, height = 24.0, u = 0.576172, v = 0.75 }
NS.StudioLettering.heading["Clone Font"] = { file = "HeadingCloneFont", width = 91.5, height = 23.5, u = 0.714844, v = 0.734375 }
NS.StudioLettering.heading["Colors & Fonts"] = { file = "HeadingColorsFonts", width = 130.5, height = 24.0, u = 0.509766, v = 0.75 }
NS.StudioLettering.heading["Combat"] = { file = "HeadingCombat", width = 65.5, height = 23.5, u = 0.511719, v = 0.734375 }
NS.StudioLettering.heading["Comic Studio Lettering"] = { file = "HeadingComicStudioLettering", width = 186.0, height = 24.0, u = 0.726562, v = 0.75 }
NS.StudioLettering.heading["Confirm Action"] = { file = "HeadingConfirmAction", width = 126.5, height = 24.0, u = 0.988281, v = 0.75 }
NS.StudioLettering.heading["Current Route"] = { file = "HeadingCurrentRoute", width = 119.5, height = 23.5, u = 0.933594, v = 0.734375 }
NS.StudioLettering.heading["Diagnostics"] = { file = "HeadingDiagnostics", width = 100.0, height = 24.0, u = 0.78125, v = 0.75 }
NS.StudioLettering.heading["Display Visibility"] = { file = "HeadingDisplayVisibility", width = 138.0, height = 24.0, u = 0.539062, v = 0.75 }
NS.StudioLettering.heading["Drift Particles"] = { file = "HeadingDriftParticles", width = 124.0, height = 23.5, u = 0.96875, v = 0.734375 }
NS.StudioLettering.heading["Equipped Trinkets"] = { file = "HeadingEquippedTrinkets", width = 144.0, height = 24.5, u = 0.5625, v = 0.765625 }
NS.StudioLettering.heading["Essentials"] = { file = "HeadingEssentials", width = 87.0, height = 23.5, u = 0.679688, v = 0.734375 }
NS.StudioLettering.heading["Fade Particles"] = { file = "HeadingFadeParticles", width = 118.5, height = 23.5, u = 0.925781, v = 0.734375 }
NS.StudioLettering.heading["Flip Particles"] = { file = "HeadingFlipParticles", width = 112.0, height = 23.5, u = 0.875, v = 0.734375 }
NS.StudioLettering.heading["Global & Panel Fonts"] = { file = "HeadingGlobalPanelFonts", width = 176.5, height = 24.0, u = 0.689453, v = 0.75 }
NS.StudioLettering.heading["Leveling Talents"] = { file = "HeadingLevelingTalents", width = 131.5, height = 24.0, u = 0.513672, v = 0.75 }
NS.StudioLettering.heading["Macro Actions"] = { file = "HeadingMacroActions", width = 125.5, height = 24.5, u = 0.980469, v = 0.765625 }
NS.StudioLettering.heading["Minimap & Data Broker"] = { file = "HeadingMinimapDataBroker", width = 193.5, height = 24.5, u = 0.755859, v = 0.765625 }
NS.StudioLettering.heading["More Settings"] = { file = "HeadingMoreSettings", width = 122.0, height = 24.5, u = 0.953125, v = 0.765625 }
NS.StudioLettering.heading["Motion"] = { file = "HeadingMotion", width = 65.0, height = 24.5, u = 0.507812, v = 0.765625 }
NS.StudioLettering.heading["Overview"] = { file = "HeadingOverview", width = 75.5, height = 24.0, u = 0.589844, v = 0.75 }
NS.StudioLettering.heading["Palettes"] = { file = "HeadingPalettes", width = 71.5, height = 23.5, u = 0.558594, v = 0.734375 }
NS.StudioLettering.heading["Particle & Additional Options"] = { file = "HeadingParticleAdditionalOptions", width = 242.0, height = 24.0, u = 0.945312, v = 0.75 }
NS.StudioLettering.heading["Pause Text"] = { file = "HeadingPauseText", width = 89.5, height = 23.5, u = 0.699219, v = 0.734375 }
NS.StudioLettering.heading["Performance"] = { file = "HeadingPerformance", width = 107.0, height = 23.5, u = 0.835938, v = 0.734375 }
NS.StudioLettering.heading["Pop! Particles"] = { file = "HeadingPopParticles", width = 119.0, height = 24.0, u = 0.929688, v = 0.75 }
NS.StudioLettering.heading["Priority Fonts"] = { file = "HeadingPriorityFonts", width = 120.5, height = 23.5, u = 0.941406, v = 0.734375 }
NS.StudioLettering.heading["Priority Placement"] = { file = "HeadingPriorityPlacement", width = 154.5, height = 23.5, u = 0.603516, v = 0.734375 }
NS.StudioLettering.heading["Priority Queue"] = { file = "HeadingPriorityQueue", width = 121.5, height = 24.0, u = 0.949219, v = 0.75 }
NS.StudioLettering.heading["Profiles"] = { file = "HeadingProfiles", width = 70.5, height = 23.5, u = 0.550781, v = 0.734375 }
NS.StudioLettering.heading["Pulse Particles"] = { file = "HeadingPulseParticles", width = 125.5, height = 23.5, u = 0.980469, v = 0.734375 }
NS.StudioLettering.heading["Quick Behavior"] = { file = "HeadingQuickBehavior", width = 124.0, height = 24.0, u = 0.96875, v = 0.75 }
NS.StudioLettering.heading["Rise Particles"] = { file = "HeadingRiseParticles", width = 116.0, height = 23.5, u = 0.90625, v = 0.734375 }
NS.StudioLettering.heading["Scatter Particles"] = { file = "HeadingScatterParticles", width = 144.5, height = 23.5, u = 0.564453, v = 0.734375 }
NS.StudioLettering.heading["Section Accents"] = { file = "HeadingSectionAccents", width = 132.0, height = 24.0, u = 0.515625, v = 0.75 }
NS.StudioLettering.heading["Slam Particles"] = { file = "HeadingSlamParticles", width = 123.0, height = 23.5, u = 0.960938, v = 0.734375 }
NS.StudioLettering.heading["Spell Importance"] = { file = "HeadingSpellImportance", width = 139.5, height = 23.5, u = 0.544922, v = 0.734375 }
NS.StudioLettering.heading["Talents"] = { file = "HeadingTalents", width = 63.0, height = 23.5, u = 0.984375, v = 0.734375 }
NS.StudioLettering.heading["Theme"] = { file = "HeadingTheme", width = 50.5, height = 23.5, u = 0.789062, v = 0.734375 }
NS.StudioLettering.heading["Trinkets & Input"] = { file = "HeadingTrinketsInput", width = 135.0, height = 24.0, u = 0.527344, v = 0.75 }
NS.StudioLettering.heading["Visibility"] = { file = "HeadingVisibility", width = 74.5, height = 24.0, u = 0.582031, v = 0.75 }
NS.StudioLettering.heading["Vortex Particles"] = { file = "HeadingVortexParticles", width = 135.5, height = 24.0, u = 0.529297, v = 0.75 }
NS.StudioLettering.heading["What Happens Next"] = { file = "HeadingWhatHappensNext", width = 155.5, height = 24.0, u = 0.607422, v = 0.75 }
NS.StudioLettering.heading["Your Adventure"] = { file = "HeadingYourAdventure", width = 127.0, height = 24.0, u = 0.992188, v = 0.75 }
NS.StudioLettering.heading["Zoom Particles"] = { file = "HeadingZoomParticles", width = 127.5, height = 23.5, u = 0.996094, v = 0.734375 }
