-- Generated by scripts/generate_studio_lettering.py; do not edit by hand.
local ADDON_NAME, NS = ...
NS.StudioLettering = { button = {}, heading = {} }
NS.StudioLettering.button["+"] = { file = "ButtonPlus", width = 16.0, height = 15.5, u = 1.0, v = 0.96875 }
NS.StudioLettering.button["Approve"] = { file = "ButtonApprove", width = 59.0, height = 18.5, u = 0.921875, v = 0.578125 }
NS.StudioLettering.button["Approved"] = { file = "ButtonApproved", width = 66.0, height = 18.5, u = 0.515625, v = 0.578125 }
NS.StudioLettering.button["Bind To This Profile"] = { file = "ButtonBindToThisProfile", width = 151.0, height = 18.5, u = 0.589844, v = 0.578125 }
NS.StudioLettering.button["Browse Builds and Imports"] = { file = "ButtonBrowseBuildsandImports", width = 190.0, height = 19.0, u = 0.742188, v = 0.59375 }
NS.StudioLettering.button["Cancel"] = { file = "ButtonCancel", width = 48.0, height = 18.0, u = 0.75, v = 0.5625 }
NS.StudioLettering.button["Change Build"] = { file = "ButtonChangeBuild", width = 89.0, height = 18.5, u = 0.695312, v = 0.578125 }
NS.StudioLettering.button["Choose a Build"] = { file = "ButtonChooseaBuild", width = 106.0, height = 18.5, u = 0.828125, v = 0.578125 }
NS.StudioLettering.button["Classic Settings"] = { file = "ButtonClassicSettings", width = 125.0, height = 18.5, u = 0.976562, v = 0.578125 }
NS.StudioLettering.button["Clear"] = { file = "ButtonClear", width = 41.5, height = 18.0, u = 0.648438, v = 0.5625 }
NS.StudioLettering.button["Close"] = { file = "ButtonClose", width = 45.0, height = 18.0, u = 0.703125, v = 0.5625 }
NS.StudioLettering.button["Confirm"] = { file = "ButtonConfirm", width = 58.0, height = 18.0, u = 0.90625, v = 0.5625 }
NS.StudioLettering.button["Copy From Profile"] = { file = "ButtonCopyFromProfile", width = 132.5, height = 18.5, u = 0.517578, v = 0.578125 }
NS.StudioLettering.button["Create"] = { file = "ButtonCreate", width = 49.5, height = 18.0, u = 0.773438, v = 0.5625 }
NS.StudioLettering.button["Delete Profile"] = { file = "ButtonDeleteProfile", width = 106.5, height = 18.5, u = 0.832031, v = 0.578125 }
NS.StudioLettering.button["Edit"] = { file = "ButtonEdit", width = 36.5, height = 18.0, u = 0.570312, v = 0.5625 }
NS.StudioLettering.button["Fit Window"] = { file = "ButtonFitWindow", width = 84.0, height = 18.5, u = 0.65625, v = 0.578125 }
NS.StudioLettering.button["New Profile"] = { file = "ButtonNewProfile", width = 88.0, height = 19.0, u = 0.6875, v = 0.59375 }
NS.StudioLettering.button["Next"] = { file = "ButtonNext", width = 38.0, height = 19.0, u = 0.59375, v = 0.59375 }
NS.StudioLettering.button["Not Set"] = { file = "ButtonNotSet", width = 61.5, height = 19.0, u = 0.960938, v = 0.59375 }
NS.StudioLettering.button["Off"] = { file = "ButtonOff", width = 31.5, height = 18.0, u = 0.984375, v = 0.5625 }
NS.StudioLettering.button["On"] = { file = "ButtonOn", width = 23.5, height = 18.0, u = 0.734375, v = 0.5625 }
NS.StudioLettering.button["Open Talents"] = { file = "ButtonOpenTalents", width = 94.5, height = 18.5, u = 0.738281, v = 0.578125 }
NS.StudioLettering.button["Preview Motion"] = { file = "ButtonPreviewMotion", width = 111.0, height = 18.5, u = 0.867188, v = 0.578125 }
NS.StudioLettering.button["Previous"] = { file = "ButtonPrevious", width = 67.0, height = 18.5, u = 0.523438, v = 0.578125 }
NS.StudioLettering.button["Rename"] = { file = "ButtonRename", width = 49.5, height = 17.5, u = 0.773438, v = 0.546875 }
NS.StudioLettering.button["Reset & Rebuild"] = { file = "ButtonResetRebuild", width = 111.0, height = 17.5, u = 0.867188, v = 0.546875 }
NS.StudioLettering.button["Reset To Defaults"] = { file = "ButtonResetToDefaults", width = 131.5, height = 18.5, u = 0.513672, v = 0.578125 }
NS.StudioLettering.button["Spend Available Points"] = { file = "ButtonSpendAvailablePoints", width = 163.5, height = 18.5, u = 0.638672, v = 0.578125 }
NS.StudioLettering.button["Switch Profile"] = { file = "ButtonSwitchProfile", width = 111.0, height = 18.5, u = 0.867188, v = 0.578125 }
NS.StudioLettering.button["Talent Options"] = { file = "ButtonTalentOptions", width = 110.0, height = 18.5, u = 0.859375, v = 0.578125 }
NS.StudioLettering.button["Tune Motion"] = { file = "ButtonTuneMotion", width = 87.5, height = 18.5, u = 0.683594, v = 0.578125 }
NS.StudioLettering.button["Unavailable"] = { file = "ButtonUnavailable", width = 81.0, height = 18.5, u = 0.632812, v = 0.578125 }
NS.StudioLettering.button["Unbind Character"] = { file = "ButtonUnbindCharacter", width = 117.0, height = 18.5, u = 0.914062, v = 0.578125 }
NS.StudioLettering.button["Undo Respec"] = { file = "ButtonUndoRespec", width = 87.5, height = 18.0, u = 0.683594, v = 0.5625 }
NS.StudioLettering.button["X"] = { file = "ButtonX", width = 16.5, height = 17.5, u = 0.515625, v = 0.546875 }
NS.StudioLettering.button["\\"] = { file = "ButtonGrip", width = 12.5, height = 17.5, u = 0.78125, v = 0.546875 }
NS.StudioLettering.button["← Talents"] = { file = "ButtonLeftTalents", width = 81.5, height = 19.5, u = 0.636719, v = 0.609375 }
NS.StudioLettering.button["↑"] = { file = "ButtonUp", width = 13.5, height = 23.0, u = 0.84375, v = 0.71875 }
NS.StudioLettering.button["↓"] = { file = "ButtonDown", width = 13.5, height = 23.0, u = 0.84375, v = 0.71875 }
NS.StudioLettering.button["−"] = { file = "ButtonMinus", width = 16.5, height = 9.5, u = 0.515625, v = 0.59375 }
NS.StudioLettering.heading["Advanced"] = { file = "HeadingAdvanced", width = 79.5, height = 25.0, u = 0.621094, v = 0.78125 }
NS.StudioLettering.heading["Animated Clone"] = { file = "HeadingAnimatedClone", width = 129.0, height = 25.0, u = 0.503906, v = 0.78125 }
NS.StudioLettering.heading["Automation & Safety"] = { file = "HeadingAutomationSafety", width = 175.0, height = 25.0, u = 0.683594, v = 0.78125 }
NS.StudioLettering.heading["BetterSBA"] = { file = "HeadingBetterSBA", width = 89.5, height = 25.0, u = 0.699219, v = 0.78125 }
NS.StudioLettering.heading["Build Automation"] = { file = "HeadingBuildAutomation", width = 145.0, height = 25.0, u = 0.566406, v = 0.78125 }
NS.StudioLettering.heading["Build Library"] = { file = "HeadingBuildLibrary", width = 112.0, height = 25.0, u = 0.875, v = 0.78125 }
NS.StudioLettering.heading["Button"] = { file = "HeadingButton", width = 63.0, height = 25.0, u = 0.984375, v = 0.78125 }
NS.StudioLettering.heading["Button & Queue"] = { file = "HeadingButtonQueue", width = 132.5, height = 25.5, u = 0.517578, v = 0.796875 }
NS.StudioLettering.heading["Button Keybind"] = { file = "HeadingButtonKeybind", width = 127.0, height = 25.5, u = 0.992188, v = 0.796875 }
NS.StudioLettering.heading["Button Keybind Font"] = { file = "HeadingButtonKeybindFont", width = 169.5, height = 25.5, u = 0.662109, v = 0.796875 }
NS.StudioLettering.heading["Cast Feedback"] = { file = "HeadingCastFeedback", width = 119.0, height = 25.0, u = 0.929688, v = 0.78125 }
NS.StudioLettering.heading["Choose a Build"] = { file = "HeadingChooseaBuild", width = 123.0, height = 25.0, u = 0.960938, v = 0.78125 }
NS.StudioLettering.heading["Class Abilities"] = { file = "HeadingClassAbilities", width = 121.0, height = 25.0, u = 0.945312, v = 0.78125 }
NS.StudioLettering.heading["Classic Animation"] = { file = "HeadingClassicAnimation", width = 148.5, height = 25.0, u = 0.580078, v = 0.78125 }
NS.StudioLettering.heading["Clone Font"] = { file = "HeadingCloneFont", width = 92.5, height = 25.0, u = 0.722656, v = 0.78125 }
NS.StudioLettering.heading["Colors & Fonts"] = { file = "HeadingColorsFonts", width = 132.0, height = 25.0, u = 0.515625, v = 0.78125 }
NS.StudioLettering.heading["Combat"] = { file = "HeadingCombat", width = 66.5, height = 25.0, u = 0.519531, v = 0.78125 }
NS.StudioLettering.heading["Comic Studio Lettering"] = { file = "HeadingComicStudioLettering", width = 187.5, height = 25.0, u = 0.732422, v = 0.78125 }
NS.StudioLettering.heading["Confirm Action"] = { file = "HeadingConfirmAction", width = 128.0, height = 25.0, u = 1.0, v = 0.78125 }
NS.StudioLettering.heading["Current Route"] = { file = "HeadingCurrentRoute", width = 120.5, height = 25.0, u = 0.941406, v = 0.78125 }
NS.StudioLettering.heading["Diagnostics"] = { file = "HeadingDiagnostics", width = 101.5, height = 25.0, u = 0.792969, v = 0.78125 }
NS.StudioLettering.heading["Display Visibility"] = { file = "HeadingDisplayVisibility", width = 139.5, height = 25.0, u = 0.544922, v = 0.78125 }
NS.StudioLettering.heading["Equipped Trinkets"] = { file = "HeadingEquippedTrinkets", width = 145.0, height = 25.5, u = 0.566406, v = 0.796875 }
NS.StudioLettering.heading["Essentials"] = { file = "HeadingEssentials", width = 88.0, height = 25.0, u = 0.6875, v = 0.78125 }
NS.StudioLettering.heading["Global & Panel Fonts"] = { file = "HeadingGlobalPanelFonts", width = 177.5, height = 25.0, u = 0.693359, v = 0.78125 }
NS.StudioLettering.heading["Leveling Talents"] = { file = "HeadingLevelingTalents", width = 133.0, height = 25.0, u = 0.519531, v = 0.78125 }
NS.StudioLettering.heading["Macro Actions"] = { file = "HeadingMacroActions", width = 126.5, height = 25.5, u = 0.988281, v = 0.796875 }
NS.StudioLettering.heading["Minimap & Data Broker"] = { file = "HeadingMinimapDataBroker", width = 195.0, height = 25.5, u = 0.761719, v = 0.796875 }
NS.StudioLettering.heading["More Settings"] = { file = "HeadingMoreSettings", width = 123.0, height = 26.0, u = 0.960938, v = 0.8125 }
NS.StudioLettering.heading["Motion"] = { file = "HeadingMotion", width = 66.0, height = 25.5, u = 0.515625, v = 0.796875 }
NS.StudioLettering.heading["Overview"] = { file = "HeadingOverview", width = 77.0, height = 25.0, u = 0.601562, v = 0.78125 }
NS.StudioLettering.heading["Palettes"] = { file = "HeadingPalettes", width = 72.5, height = 25.0, u = 0.566406, v = 0.78125 }
NS.StudioLettering.heading["Particle & Additional Options"] = { file = "HeadingParticleAdditionalOptions", width = 243.5, height = 25.0, u = 0.951172, v = 0.78125 }
NS.StudioLettering.heading["Pause Text"] = { file = "HeadingPauseText", width = 91.0, height = 25.0, u = 0.710938, v = 0.78125 }
NS.StudioLettering.heading["Performance"] = { file = "HeadingPerformance", width = 108.5, height = 25.0, u = 0.847656, v = 0.78125 }
NS.StudioLettering.heading["Priority Fonts"] = { file = "HeadingPriorityFonts", width = 122.0, height = 25.0, u = 0.953125, v = 0.78125 }
NS.StudioLettering.heading["Priority Placement"] = { file = "HeadingPriorityPlacement", width = 155.5, height = 25.0, u = 0.607422, v = 0.78125 }
NS.StudioLettering.heading["Priority Queue"] = { file = "HeadingPriorityQueue", width = 122.5, height = 25.5, u = 0.957031, v = 0.796875 }
NS.StudioLettering.heading["Profiles"] = { file = "HeadingProfiles", width = 72.0, height = 25.0, u = 0.5625, v = 0.78125 }
NS.StudioLettering.heading["Quick Behavior"] = { file = "HeadingQuickBehavior", width = 125.0, height = 25.5, u = 0.976562, v = 0.796875 }
NS.StudioLettering.heading["Section Accents"] = { file = "HeadingSectionAccents", width = 133.0, height = 25.0, u = 0.519531, v = 0.78125 }
NS.StudioLettering.heading["Spell Importance"] = { file = "HeadingSpellImportance", width = 140.5, height = 25.0, u = 0.548828, v = 0.78125 }
NS.StudioLettering.heading["Talents"] = { file = "HeadingTalents", width = 64.0, height = 25.0, u = 1.0, v = 0.78125 }
NS.StudioLettering.heading["Theme"] = { file = "HeadingTheme", width = 52.0, height = 25.0, u = 0.8125, v = 0.78125 }
NS.StudioLettering.heading["Trinkets & Input"] = { file = "HeadingTrinketsInput", width = 136.5, height = 25.0, u = 0.533203, v = 0.78125 }
NS.StudioLettering.heading["Visibility"] = { file = "HeadingVisibility", width = 76.0, height = 25.0, u = 0.59375, v = 0.78125 }
NS.StudioLettering.heading["What Happens Next"] = { file = "HeadingWhatHappensNext", width = 157.0, height = 25.5, u = 0.613281, v = 0.796875 }
NS.StudioLettering.heading["Your Adventure"] = { file = "HeadingYourAdventure", width = 128.0, height = 25.0, u = 1.0, v = 0.78125 }
