local ADDON_NAME, NS = ...

NS.TALENT_BUILD_CUSTOM_ID = "CUSTOM"
NS.TALENT_BUILD_FILTER_ALL = "All"
NS.TALENT_BUILD_TYPE_BUILTIN = "Built-In"
NS.TALENT_BUILD_TYPE_USER = "User"
NS.TALENT_BUILD_TYPE_CUSTOM = "Custom"
NS.TALENT_BUILD_TYPES = {
    NS.TALENT_BUILD_TYPE_BUILTIN,
    NS.TALENT_BUILD_TYPE_USER,
    NS.TALENT_BUILD_TYPE_CUSTOM,
}
NS.TALENT_BUILD_RATINGS = { "S", "A", "B", "C", "D" }
NS.TALENT_BUILD_AUTO_APPLY_MODES = { "Auto-Apply", "Prompt Before Spending" }
NS.TALENT_BUILD_SOURCES = {
    NS.TALENT_BUILD_FILTER_ALL,
    "Icy Veins",
    "Noxxic",
    "Wowhead",
    "LazyGrip",
    "Discord",
    "Custom",
}
NS.TALENT_BUILD_SOURCE_URLS = {
    ["Icy Veins"] = "https://www.icy-veins.com/wow/news/single-button-assistant-and-assisted-highlight-design-intentions/",
    ["Noxxic"] = "https://www.noxxic.com/wow/",
    ["Wowhead"] = "https://www.wowhead.com/guide/classes",
    ["LazyGrip"] = "https://lazygrip.net/",
    ["Discord"] = "",
    ["Custom"] = "",
}
NS.TALENT_BUILD_CATALOG = {
    version = 5,
    checkedAt = "2026-09-24",
    entries = {
        {
            id = "USER-SBA-103-META-20260924",
            classToken = "DRUID",
            specID = 103,
            name = "Feral Druid - Druid of the Claw (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Druid of the Claw",
            contentType = "General SBA / user-supplied meta",
            importString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2M2mZZGzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-267-HELLCALLER-MPLUS-20260924",
            classToken = "WARLOCK",
            specID = 267,
            name = "Destruction Warlock - Hellcaller (Mythic+ SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Hellcaller",
            contentType = "Mythic+ (user supplied)",
            importString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzysNzMjFzYZZmBAAzgZmZxCMwsY0YGAzWsxAAAjZYAAwMDGzMmZDAAwMzMDAAzwA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-267-DIABOLIST-20260924",
            classToken = "WARLOCK",
            specID = 267,
            name = "Destruction Warlock - Diabolist (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Diabolist",
            contentType = "General SBA / user-supplied meta",
            importString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNbmZ2mZGzysZmZmFzMLLzDMAAYGjZmZBMmxwCZgthFaswAAAjZYAAmZAGzYMbAAAmZmBAAGG",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-105-META-20260924",
            classToken = "DRUID",
            specID = 105,
            name = "Restoration Druid - Wildstalker (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Wildstalker",
            contentType = "General SBA / user-supplied meta",
            importString = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNMMzsNsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZm8AzAAAAAAAgBAgAAAmtZ2a2mZxGjZGYmFQzAAMzAwA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. SBA chooses damage actions; passive damage-to-healing effects may trigger, but it does not choose healing targets or manage triage. Healing spells, utility and defensive decisions remain manual. Live tree validation is required.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-262-META-20260924",
            classToken = "SHAMAN",
            specID = 262,
            name = "Elemental Shaman - Farseer (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Farseer",
            contentType = "General SBA / user-supplied meta",
            importString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZbZMmhZAAAAgFzsBDYAzGTIzCAMbzMzYstYajZmtxyMmZMmlZZmZZYMzsAAMAwMjhhB",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-251-META-20260924",
            classToken = "DEATHKNIGHT",
            specID = 251,
            name = "Frost Death Knight - Deathbringer (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Deathbringer",
            contentType = "General SBA / user-supplied meta",
            importString = "CsPAAAAAAAAAAAAAAAAAAAAAAMAzMMjZYY2mZmZmZxMjmZMGDzMGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAzAD",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-254-META-20260924",
            classToken = "HUNTER",
            specID = 254,
            name = "Marksmanship Hunter - Sentinel (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Sentinel",
            contentType = "General SBA / user-supplied meta",
            importString = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGNWGQmBbAAAAAAAAgZMzMjtZMzMmhtx0MGMLbLzMzMzMzMzCzsMMDAAgHYMGAmpNwAsxMbzYA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-104-META-20260924",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian Druid - Elune's Chosen (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Elune's Chosen",
            contentType = "General SBA / user-supplied meta",
            importString = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsYmZMziZxMmZZZgZzwoJamZWGzMzsMmBAAAAAgZmNDYZbmBjZZAMFAAAYzYmHAYxYYALWAYmBwA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-253-META-20260924",
            classToken = "HUNTER",
            specID = 253,
            name = "Beast Mastery Hunter - Pack Leader (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Pack Leader",
            contentType = "General SBA / user-supplied meta",
            importString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzohG2AAwMmZmZ5BmxMzMzYmBzMmZYmxMzM2mZGzYG2GTzAAAAAAAAAPwYMgZ2IgZBsNAA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-268-META-20260924",
            classToken = "MONK",
            specID = 268,
            name = "Brewmaster Monk - Master of Harmony (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Master of Harmony",
            contentType = "General SBA / user-supplied meta",
            importString = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZbzYGGzyMzGzMjBAAAAAAYZBmwMYmB2MMmZmZMzGzMmZZYZ7B22mNMLAAwysMtMbzsMAAQAMsBmZATjBAAMA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-255-META-20260924",
            classToken = "HUNTER",
            specID = 255,
            name = "Survival Hunter - Sentinel (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Sentinel",
            contentType = "General SBA / user-supplied meta",
            importString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmxMz2MAAAAAAmxMzM2mxYGzgx0MAAAADAwy2MjlZMzYMmZAYGbgxwMbGAA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-256-META-20260924",
            classToken = "PRIEST",
            specID = 256,
            name = "Discipline Priest - Oracle (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Oracle",
            contentType = "General SBA / user-supplied meta",
            importString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMzwYmBbmmJGgZWwQYMLDwYwCAAMmZmxgZAmZGBzA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. SBA chooses damage actions; passive damage-to-healing effects may trigger, but it does not choose healing targets or manage triage. Healing spells, utility and defensive decisions remain manual. Live tree validation is required.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-258-META-20260924",
            classToken = "PRIEST",
            specID = 258,
            name = "Shadow Priest - Voidweaver (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Voidweaver",
            contentType = "General SBA / user-supplied meta",
            importString = "CIQAAAAAAAAAAAAAAAAAAAAAAMjZMAAAAAAAAAAAAYMLzMGbzMmZ2mZGjx2MzYmZGbIDLbz0AMzMDAEgZb22CmNGAYwYmZGz2YGMzgZwA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-269-META-20260924",
            classToken = "MONK",
            specID = 269,
            name = "Windwalker Monk - Shado-Pan (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Shado-Pan",
            contentType = "General SBA / user-supplied meta",
            importString = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYAMGbzMz2MAAAAAAAAAAAALDzEmhhBMjhZmZGmthZYWmJAgFzsNzMmZmZAAsBgmlZpZmZWAwAzMAMWGIGwA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-252-META-20260924",
            classToken = "DEATHKNIGHT",
            specID = 252,
            name = "Unholy Death Knight - Rider of the Apocalypse (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Rider of the Apocalypse",
            contentType = "General SBA / user-supplied meta",
            importString = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMjBz2MzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-102-META-20260924",
            classToken = "DRUID",
            specID = 102,
            name = "Balance Druid - Elune's Chosen (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Elune's Chosen",
            contentType = "General SBA / user-supplied meta",
            importString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDwsMmZmZhBjZZmlZWYmxGLzsMmZM2wwAM22mZwY2GBmAAAAswMzMD2MmxYAAYmBLDA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-250-LEVELING-20260924",
            classToken = "DEATHKNIGHT",
            specID = 250,
            name = "Blood Death Knight - San'layn (Leveling / Delves / Dungeons)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "San'layn",
            contentType = "Leveling / Delves / Dungeons",
            importString = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmZMbzMz0MLmZMzMAAAAAmhZmZmZMzYAAzMzMzAAAYgBmxiGLbgsNgNAzYAAAmZAMA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-250-RAIDS-20260924",
            classToken = "DEATHKNIGHT",
            specID = 250,
            name = "Blood Death Knight - San'layn (Raids)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "San'layn",
            contentType = "Raids",
            importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZZmZmmZxMzMmxAAAAAzMmZmZmZGzMjBAMzMzAAAYgBmxmGLLgsMgNAzwAAAmZghB",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. This raid import carries a nonzero talent-tree hash that must match the running client. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-270-META-20260924",
            classToken = "MONK",
            specID = 270,
            name = "Mistweaver Monk - Conduit of the Celestials (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Conduit of the Celestials",
            contentType = "General SBA / user-supplied meta",
            importString = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgBWmZZML2mxMz2mBmhZzMbLLzMWYMNjZADGAzMzMMbYGmlZCAAAAgAsYbmtZbmJAAMYMAzAGDsIjZA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. SBA chooses damage actions; passive damage-to-healing effects may trigger, but it does not choose healing targets or manage triage. Healing spells, utility and defensive decisions remain manual. Live tree validation is required.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-71-META-20260924",
            classToken = "WARRIOR",
            specID = 71,
            name = "Arms Warrior - Slayer (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Slayer",
            contentType = "General SBA / user-supplied meta",
            importString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGmxyMzMzwMmZAAAAAMWmZgJMW2GYBMgZYCZGsBmZYsMYWmZbAmZAwMMA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-264-META-20260924",
            classToken = "SHAMAN",
            specID = 264,
            name = "Restoration Shaman - Totemic (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Totemic",
            contentType = "General SBA / user-supplied meta",
            importString = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsstMmZmZMzMjZMsAbwMW0YbAZGYjZmBz2MjRzyyMzmZMbsYMzYYZWGAAMAmZwMDAMYA",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. SBA chooses damage actions; passive damage-to-healing effects may trigger, but it does not choose healing targets or manage triage. Healing spells, utility and defensive decisions remain manual. Live tree validation is required.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "USER-SBA-263-META-20260924",
            classToken = "SHAMAN",
            specID = 263,
            name = "Enhancement Shaman - Stormbringer (User SBA target)",
            author = "User supplied",
            rating = "",
            source = "Custom",
            catalogSource = "Custom",
            sourceURL = "",
            patch = "",
            checkedAt = "2026-09-24",
            verificationStatus = "user-provided",
            heroTree = "Stormbringer",
            contentType = "General SBA / user-supplied meta",
            importString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbkFYGGawCAz2MmxYZZGbMzsNWmZmZYsMmBAYGGzMMCMzgBjB",
            notes = "Exact user-supplied SBA/meta target; no publisher or performance verification supplied. Talent encoding was checked offline; patch and live tree compatibility must be checked in-game. Continue to manage unsupported cooldowns, defensives and utility manually.",
            category = "User-supplied SBA target",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-267-DIABOLIST-AOE-20260924",
            classToken = "WARLOCK",
            specID = 267,
            name = "Destruction Warlock - Diabolist (SBA inferred AoE)",
            author = "Loozy",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/destruction/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/warlock/destruction/rotation-cooldowns-pve-dps",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-29",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Diabolist",
            contentType = "Mythic+ / AoE",
            importString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNbmZ2mZGzysZmZmFzMLLzDMAAYGjZmZBMmxwCZgthFaswAAAjZYAAmZAGzYMbAAAmZmBAAGG",
            notes = "The author recommends Mayhem when Havoc would otherwise go unused with SBA. These exact general AoE exports already select Mayhem; whole-build suitability is BetterSBA inference. Infernal and other cooldowns still need manual use. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-267-HELLCALLER-AOE-20260924",
            classToken = "WARLOCK",
            specID = 267,
            name = "Destruction Warlock - Hellcaller (SBA inferred AoE)",
            author = "Loozy",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/destruction/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/warlock/destruction/rotation-cooldowns-pve-dps",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-29",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Hellcaller",
            contentType = "Mythic+ / AoE",
            importString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzysNzMjFzYZZmBAAzgZmZxCMwsY0YGAzWsxAAAjZYAAwMDGzMmZDAAwMzMDAAzwA",
            notes = "The author recommends Mayhem when Havoc would otherwise go unused with SBA. These exact general AoE exports already select Mayhem; whole-build suitability is BetterSBA inference. Infernal and other cooldowns still need manual use. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-1467-SCALECOMMANDER-ST-20260924",
            classToken = "EVOKER",
            specID = 1467,
            name = "Devastation Evoker - Scalecommander (SBA inferred raid)",
            author = "Preheat",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-09-23",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Scalecommander",
            contentType = "Raid / single target",
            importString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwMDzwMgBjZaMzMNzM2mZmZmZmZmZGwMmZGzMLzMDMwYwGsMGN2GQmBBbYgZGMjHA",
            notes = "The basics author describes Devastation as suitable for SBA with manual Dragonrage, Deep Breath and utility. Applying this to exact general hero builds is BetterSBA inference; rapid presses can still cancel channels or empowers. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-1467-SCALECOMMANDER-AOE-20260924",
            classToken = "EVOKER",
            specID = 1467,
            name = "Devastation Evoker - Scalecommander (SBA inferred AoE)",
            author = "Preheat",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-09-23",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Scalecommander",
            contentType = "Mythic+ / AoE",
            importString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwgZGmBGYMTjZmpZmZ2mZmZmZmZmZGwMzMzYmZZmZgBGD2glxox2AyMIYDzgZGM8AA",
            notes = "The basics author describes Devastation as suitable for SBA with manual Dragonrage, Deep Breath and utility. Applying this to exact general hero builds is BetterSBA inference; rapid presses can still cancel channels or empowers. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-1467-FLAMESHAPER-ST-20260924",
            classToken = "EVOKER",
            specID = 1467,
            name = "Devastation Evoker - Flameshaper (SBA inferred raid)",
            author = "Preheat",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-09-23",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Flameshaper",
            contentType = "Raid / single target",
            importString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZwMDGMgBjZamZmJjxyMzMzwMzMzAmxMzYmZZmZwMwMmB2ALgZYCsFsMMAmZGG",
            notes = "The basics author describes Devastation as suitable for SBA with manual Dragonrage, Deep Breath and utility. Applying this to exact general hero builds is BetterSBA inference; rapid presses can still cancel channels or empowers. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-1467-FLAMESHAPER-AOE-20260924",
            classToken = "EVOKER",
            specID = 1467,
            name = "Devastation Evoker - Flameshaper (SBA inferred AoE)",
            author = "Preheat",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-09-23",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Flameshaper",
            contentType = "Mythic+ / AoE",
            importString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwMjZGzMwMGDTDzMZM2mZmZGGzMzAmZmxYmZbmZwMwMmBWAbgZYCsFsMMDwMzwA",
            notes = "The basics author describes Devastation as suitable for SBA with manual Dragonrage, Deep Breath and utility. Applying this to exact general hero builds is BetterSBA inference; rapid presses can still cancel channels or empowers. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-71-SLAYER-ST-20260924",
            classToken = "WARRIOR",
            specID = 71,
            name = "Arms Warrior - Slayer (SBA inferred raid)",
            author = "Archimtiros",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/arms/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/warrior/arms/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Slayer",
            contentType = "Raid / single target",
            importString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZAhxyyALgBMDTIzgNwMjtx2ALzsMAzMAYGGA",
            notes = "The basics author describes Arms SBA as capable when players manage defensive, mobility and utility spells. These exact hero/content exports remain general recommendations selected here by BetterSBA inference. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-71-SLAYER-AOE-20260924",
            classToken = "WARRIOR",
            specID = 71,
            name = "Arms Warrior - Slayer (SBA inferred AoE)",
            author = "Archimtiros",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/arms/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/warrior/arms/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Slayer",
            contentType = "Mythic+ / AoE",
            importString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2AbgBMDTIzgNwMDDDmlZ2GgZGAMDDA",
            notes = "The basics author describes Arms SBA as capable when players manage defensive, mobility and utility spells. These exact hero/content exports remain general recommendations selected here by BetterSBA inference. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-71-COLOSSUS-ST-20260924",
            classToken = "WARRIOR",
            specID = 71,
            name = "Arms Warrior - Colossus (SBA inferred raid)",
            author = "Archimtiros",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/arms/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/warrior/arms/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Colossus",
            contentType = "Raid / single target",
            importString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzwMDAAAghphxYmxyMzMzgxMDAAAAgZ2mZABwmZMsBDMj2oxgFwMjtx2MzmlZWGMzAAMDDA",
            notes = "The basics author describes Arms SBA as capable when players manage defensive, mobility and utility spells. These exact hero/content exports remain general recommendations selected here by BetterSBA inference. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-71-COLOSSUS-AOE-20260924",
            classToken = "WARRIOR",
            specID = 71,
            name = "Arms Warrior - Colossus (SBA inferred AoE)",
            author = "Archimtiros",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/arms/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/warrior/arms/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Colossus",
            contentType = "Mythic+ / AoE",
            importString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMzYGAAAghphxYmZzMzMzYmxMDAAAAgxmZgJLAbmxwCMwMajGDWAzMMMGzmZbwMDAwMMA",
            notes = "The basics author describes Arms SBA as capable when players manage defensive, mobility and utility spells. These exact hero/content exports remain general recommendations selected here by BetterSBA inference. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-259-DEATHSTALKER-ST-20260924",
            classToken = "ROGUE",
            specID = 259,
            name = "Assassination Rogue - Deathstalker (SBA inferred raid)",
            author = "Whispyr",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/assassination/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/rogue/assassination/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-09-06",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Deathstalker",
            contentType = "Raid / single target",
            importString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAYWGsNDAAAAAottZmZmZmxYZmZmtZWmZmZMjZMGzMGGgNzyADYJYZYCMsAmZAGjB",
            notes = "The basics guide finds SBA much stronger on single targets than in AoE. Only exact single-target builds are included; Deathmark, Kingsbane and utility remain manual. Whole-build SBA suitability is BetterSBA inference. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-INFERRED-259-FATEBOUND-ST-20260924",
            classToken = "ROGUE",
            specID = 259,
            name = "Assassination Rogue - Fatebound (SBA inferred raid)",
            author = "Whispyr",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/assassination/talent-builds-pve-dps",
            evidenceURL = "https://www.wowhead.com/guide/classes/rogue/assassination/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-09-06",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Fatebound",
            contentType = "Raid / single target",
            importString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAYWGsNDAAAAAottZmZmZmxYZmZmtZWmZmZMjZMGzMGGADsAzY0Y2AZbAbGAMzMYA",
            notes = "The basics guide finds SBA much stronger on single targets than in AoE. Only exact single-target builds are included; Deathmark, Kingsbane and utility remain manual. Whole-build SBA suitability is BetterSBA inference. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-IV-INFERRED-1473-CHRONOWARDEN-20260924",
            classToken = "EVOKER",
            specID = 1473,
            name = "Augmentation Evoker - Chronowarden (SBA inferred raid)",
            author = "Saeldur",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/augmentation-evoker-pve-dps-easy-mode",
            evidenceURL = "https://www.icy-veins.com/wow/augmentation-evoker-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-10",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Chronowarden",
            contentType = "Raid / general PvE",
            importString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgBzMLzYmZMzGAAAAAAAAzMMmBjpGzMzAAAAgZMjxMzyYmBmZzAjZswCMwMM0ALYMmZAgB",
            notes = "The author recommends the assistant as an accessible entry point with manual cooldowns and warns that rapid presses can cancel empowers. These exact beginner exports are general builds; current whole-build SBA suitability is inference, despite historical assistant-related simplification notes. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-IV-INFERRED-1473-SCALECOMMANDER-20260924",
            classToken = "EVOKER",
            specID = 1473,
            name = "Augmentation Evoker - Scalecommander (SBA inferred AoE)",
            author = "Saeldur",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/augmentation-evoker-pve-dps-easy-mode",
            evidenceURL = "https://www.icy-veins.com/wow/augmentation-evoker-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-10",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-inferred",
            heroTree = "Scalecommander",
            contentType = "Mythic+ / Delves",
            importString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmtZMzMmBAAAAAAAAmhHYGYM1YmZGAAAAMzMjxMz2YmBmZzYwCsMGGbDgZQshxMYmBDG",
            notes = "The author recommends the assistant as an accessible entry point with manual cooldowns and warns that rapid presses can cancel empowers. These exact beginner exports are general builds; current whole-build SBA suitability is inference, despite historical assistant-related simplification notes. Exact publisher export unchanged; not simulated or tested in-game.",
            category = "SBA guide inference",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "BSBA-WH-SBA-COMPATIBLE-63-TARGETED-20260924",
            classToken = "MAGE",
            specID = 63,
            name = "Fire Mage - Sunfury (SBA guide adaptation)",
            author = "Preheat; adapted by BetterSBA",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-adapted",
            heroTree = "Sunfury",
            contentType = "Raid and Mythic+ starter",
            importString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzIzMzAAAwAAmZmmltlZAA2MzM2mZmZGLAAAAAYxMjZAAgZMmZmZMzsNAMzQGjBMDjB",
            notes = "BetterSBA adaptation of the author's SBA-compatible starter: changes only Flamestrike to the targeted choice recommended in the guide text. Not an author-published export or simulation-ranked result. Manually use Combustion, trinkets, racials and other items. Not tested in-game.",
            category = "SBA guide adaptation",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-251-20260812",
            classToken = "DEATHKNIGHT",
            specID = 251,
            name = "Frost Death Knight - Deathbringer (SBA-compatible)",
            author = "khazakdk",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Deathbringer",
            contentType = "General beginner PvE",
            importString = "CsPAAAAAAAAAAAAAAAAAAAAAAMDwMmZmZAzmZmZmZxMjmZMzAzMGMmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMzMzADADzMAzAD",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. The beginner build omits some capstone choices to simplify its rotation.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-253-20260812",
            classToken = "HUNTER",
            specID = 253,
            name = "Beast Mastery Hunter - Pack Leader (SBA-compatible)",
            author = "Tarlo",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Pack Leader",
            contentType = "Open world, delves and Mythic+",
            importString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGPwMzsMzwMzMjZGMzYmhZmZGzwMzwYmhx0MAAAAAAAAYMmBYmNCWmZBsNAM",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. Manually handle items, utility and pet management. The author notes SBA misses minor optimizations.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-258-20260812",
            classToken = "PRIEST",
            specID = 258,
            name = "Shadow Priest - Voidweaver (SBA-compatible)",
            author = "EllipsisPriest",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Voidweaver",
            contentType = "General beginner PvE",
            importString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxDMLmxgZMzsMzwMsMzMmZmxCyMWQjBmZmBACwsNbLgZjBYmBZMzMjZbmZwMDmJGA",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. Use Power Infusion manually and manage utility, defensives and items yourself.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-268-20260812",
            classToken = "MONK",
            specID = 268,
            name = "Brewmaster Monk - Master of Harmony (SBA-compatible)",
            author = "Sinzhu",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Master of Harmony",
            contentType = "Beginner PvE; strongest assistant fit in single target",
            importString = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzYWmxmxMjBAAAAAAYZBjYmBmhxmZwMzMDzyYmxY5BYZzy2sNMLAAwysMtMbzsMAAQAMsAmZATjBMAgB",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. Defensive abilities still need manual use. The guide reports weaker SBA behavior in AoE.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-577-sba-fel-scarred-raid",
            classToken = "DEMONHUNTER",
            specID = 577,
            name = "Havoc - SBA Fel-Scarred Raid",
            author = "Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-30",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Fel-Scarred",
            contentType = "Raid",
            importString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMjZMzMzMmJjZGAAAAAAwsZMbzMGDegZsMz8AzwMjxsMw2sZGDzGTjZmxwGAAAAAAAAzMYAAAAYA",
            notes = "Author's Rotation Assist alternative. Manually use Metamorphosis, The Hunt, and movement abilities including Felblade; utility and defensives remain manual. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-577-sba-fel-scarred-dungeon",
            classToken = "DEMONHUNTER",
            specID = 577,
            name = "Havoc - SBA Fel-Scarred Dungeon",
            author = "Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-30",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Fel-Scarred",
            contentType = "Dungeon",
            importString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyAbzmZMMbMNmZGzYDAAAYAAAAMzgBAAAgB",
            notes = "Author's Rotation Assist alternative. Manually use Metamorphosis, The Hunt, and movement abilities including Felblade; utility and defensives remain manual. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-1480-sba-annihilator-single-target",
            classToken = "DEMONHUNTER",
            specID = 1480,
            name = "Devourer - SBA Annihilator Single Target",
            author = "Voodoo, Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-10",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Annihilator",
            contentType = "Single Target",
            importString = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMjZmZmZmFzYsolFmZmZ2abmZGAzYAIgxghB",
            notes = "Author's least-impacted Assist alternative, with major SBA limitations. Manually use Void Metamorphosis, Collapsing Star, The Hunt, movement, utility and defensives. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-1480-sba-annihilator-aoe",
            classToken = "DEMONHUNTER",
            specID = 1480,
            name = "Devourer - SBA Annihilator AoE",
            author = "Voodoo, Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-10",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Annihilator",
            contentType = "AoE",
            importString = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFtswMzMzWbzMzAYGDABMGMmB",
            notes = "Author's least-impacted Assist alternative, with major SBA limitations. Manually use Void Metamorphosis, Collapsing Star, The Hunt, movement, utility and defensives. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-104-guardian-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmZml5BmZMWMLeg5BmZZZgZzMGNRzMziZmZmlxMAAAAAAMsNDYZbmBjZZAMFAAAYDz8ADYxMYwglNAzMAG",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-104-guardian-raids",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian - Raids",
            author = "Dvalin",
            rating = "A",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmZml5BmZM2MLj5BMLLDMbwoJamZWmZmZGjZAAAAAAYMbzA22mZwY2GATBAAA2MmZAWMDGMYZbAmZAM",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-103-feral-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 103,
            name = "Feral - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAmZ2MzMzMmZ2M2GbzMzMPwMDAAAALBzmxwMjaGziZmZmlxMDAAAAAAGAAAAgmZZ2mZmBEYBMzAswgBAAwMbYA",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-103-feral-raids",
            classToken = "DRUID",
            specID = 103,
            name = "Feral - Raids",
            author = "Dvalin",
            rating = "A",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtlxyMbzYGzMDAAAALBzmhxMjaGziZmZGjZYAAAAAAMwAAAAIAYWmZpZbmlNwMDwiZwAAYmBAD",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-102-balance-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 102,
            name = "Balance - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmZhBMmZZmFzMzsMWmZZMzgNMAYssNzgxsNCMBAAAYhZmZGsZYMGAAmZgB",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-102-balance-raids",
            classToken = "DRUID",
            specID = 102,
            name = "Balance - Raids",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmhBDjZWGLzYGbjlZMmZGzCGAMALbjNMNzsMCAAAwmZmZmBbGYMDgZGAYA",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
    },
}
