local ADDON_NAME, NS = ...

NS.TALENT_BUILD_CUSTOM_ID = "CUSTOM"
NS.TALENT_BUILD_FILTER_ALL = "All"
NS.TALENT_BUILD_TYPE_BUILTIN = "Built-In"
NS.TALENT_BUILD_TYPE_USER = "User"
NS.TALENT_BUILD_TYPE_CUSTOM = "Custom"
NS.TALENT_BUILD_TYPES = {
    NS.TALENT_BUILD_TYPE_BUILTIN,
    NS.TALENT_BUILD_TYPE_USER,
    NS.TALENT_BUILD_TYPE_CUSTOM,
}
NS.TALENT_BUILD_RATINGS = { "S", "A", "B", "C", "D" }
NS.TALENT_BUILD_AUTO_APPLY_MODES = { "Auto-Apply", "Prompt Before Spending" }
NS.TALENT_BUILD_SOURCES = {
    NS.TALENT_BUILD_FILTER_ALL,
    "Icy Veins",
    "Noxxic",
    "Wowhead",
    "Discord",
    "Custom",
}
NS.TALENT_BUILD_SOURCE_URLS = {
    ["Icy Veins"] = "https://www.icy-veins.com/wow/news/single-button-assistant-and-assisted-highlight-design-intentions/",
    ["Noxxic"] = "https://www.noxxic.com/wow/",
    ["Wowhead"] = "https://www.wowhead.com/guide/classes",
    ["Discord"] = "",
    ["Custom"] = "",
}
NS.TALENT_BUILD_CATALOG = {
    version = 2,
    checkedAt = "2026-09-24",
    entries = {
        {
            id = "BSBA-WH-SBA-COMPATIBLE-63-TARGETED-20260924",
            classToken = "MAGE",
            specID = 63,
            name = "Fire Mage - Sunfury (SBA guide adaptation)",
            author = "Preheat; adapted by BetterSBA",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "guide-adapted",
            heroTree = "Sunfury",
            contentType = "Raid and Mythic+ starter",
            importString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzIzMzAAAwAAmZmmltlZAA2MzM2mZmZGLAAAAAYxMjZAAgZMmZmZMzsNAMzQGjBMDjB",
            notes = "BetterSBA adaptation of the author's SBA-compatible starter: changes only Flamestrike to the targeted choice recommended in the guide text. Not an author-published export or simulation-ranked result. Manually use Combustion, trinkets, racials and other items. Not tested in-game.",
            category = "SBA guide adaptation",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-251-20260812",
            classToken = "DEATHKNIGHT",
            specID = 251,
            name = "Frost Death Knight - Deathbringer (SBA-compatible)",
            author = "khazakdk",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Deathbringer",
            contentType = "General beginner PvE",
            importString = "CsPAAAAAAAAAAAAAAAAAAAAAAMDwMmZmZAzmZmZmZxMjmZMzAzMGMmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMzMzADADzMAzAD",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. The beginner build omits some capstone choices to simplify its rotation.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-253-20260812",
            classToken = "HUNTER",
            specID = 253,
            name = "Beast Mastery Hunter - Pack Leader (SBA-compatible)",
            author = "Tarlo",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Pack Leader",
            contentType = "Open world, delves and Mythic+",
            importString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGPwMzsMzwMzMjZGMzYmhZmZGzwMzwYmhx0MAAAAAAAAYMmBYmNCWmZBsNAM",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. Manually handle items, utility and pet management. The author notes SBA misses minor optimizations.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-258-20260812",
            classToken = "PRIEST",
            specID = 258,
            name = "Shadow Priest - Voidweaver (SBA-compatible)",
            author = "EllipsisPriest",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Voidweaver",
            contentType = "General beginner PvE",
            importString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxDMLmxgZMzsMzwMsMzMmZmxCyMWQjBmZmBACwsNbLgZjBYmBZMzMjZbmZwMDmJGA",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. Use Power Infusion manually and manage utility, defensives and items yourself.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "WH-SBA-COMPATIBLE-268-20260812",
            classToken = "MONK",
            specID = 268,
            name = "Brewmaster Monk - Master of Harmony (SBA-compatible)",
            author = "Sinzhu",
            rating = "",
            source = "Wowhead",
            catalogSource = "Wowhead",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/basics",
            patch = "12.1.0",
            sourceUpdatedAt = "2026-08-12",
            checkedAt = "2026-09-24",
            verificationStatus = "source-compatible",
            heroTree = "Master of Harmony",
            contentType = "Beginner PvE; strongest assistant fit in single target",
            importString = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzYWmxmxMjBAAAAAAYZBjYmBmhxmZwMzMDzyYmxY5BYZzy2sNMLAAwysMtMbzsMAAQAMsAmZATjBMAgB",
            notes = "Author-recommended SBA-compatible starter; not an SBA optimization result. Defensive abilities still need manual use. The guide reports weaker SBA behavior in AoE.",
            category = "SBA-compatible starter",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-577-sba-fel-scarred-raid",
            classToken = "DEMONHUNTER",
            specID = 577,
            name = "Havoc - SBA Fel-Scarred Raid",
            author = "Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-30",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Fel-Scarred",
            contentType = "Raid",
            importString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMjZMzMzMmJjZGAAAAAAwsZMbzMGDegZsMz8AzwMjxsMw2sZGDzGTjZmxwGAAAAAAAAzMYAAAAYA",
            notes = "Author's Rotation Assist alternative. Manually use Metamorphosis, The Hunt, and movement abilities including Felblade; utility and defensives remain manual. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-577-sba-fel-scarred-dungeon",
            classToken = "DEMONHUNTER",
            specID = 577,
            name = "Havoc - SBA Fel-Scarred Dungeon",
            author = "Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-30",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Fel-Scarred",
            contentType = "Dungeon",
            importString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyAbzmZMMbMNmZGzYDAAAYAAAAMzgBAAAgB",
            notes = "Author's Rotation Assist alternative. Manually use Metamorphosis, The Hunt, and movement abilities including Felblade; utility and defensives remain manual. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-1480-sba-annihilator-single-target",
            classToken = "DEMONHUNTER",
            specID = 1480,
            name = "Devourer - SBA Annihilator Single Target",
            author = "Voodoo, Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-10",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Annihilator",
            contentType = "Single Target",
            importString = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMjZmZmZmFzYsolFmZmZ2abmZGAzYAIgxghB",
            notes = "Author's least-impacted Assist alternative, with major SBA limitations. Manually use Void Metamorphosis, Collapsing Star, The Hunt, movement, utility and defensives. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "ICY-1480-sba-annihilator-aoe",
            classToken = "DEMONHUNTER",
            specID = 1480,
            name = "Devourer - SBA Annihilator AoE",
            author = "Voodoo, Wordup",
            rating = "",
            source = "Icy Veins",
            catalogSource = "Icy Veins",
            sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-easy-mode",
            patch = "12.1",
            sourceUpdatedAt = "2026-08-10",
            checkedAt = "2026-09-24",
            verificationStatus = "source-sba",
            heroTree = "Annihilator",
            contentType = "AoE",
            importString = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFtswMzMzWbzMzAYGDABMGMmB",
            notes = "Author's least-impacted Assist alternative, with major SBA limitations. Manually use Void Metamorphosis, Collapsing Star, The Hunt, movement, utility and defensives. Source verified; not tested in-game or proven optimal at every level.",
            category = "SBA source build",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-104-guardian-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmZml5BmZMWMLeg5BmZZZgZzMGNRzMziZmZmlxMAAAAAAMsNDYZbmBjZZAMFAAAYDz8ADYxMYwglNAzMAG",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-104-guardian-raids",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian - Raids",
            author = "Dvalin",
            rating = "A",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmZml5BmZM2MLj5BMLLDMbwoJamZWmZmZGjZAAAAAAYMbzA22mZwY2GATBAAA2MmZAWMDGMYZbAmZAM",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-103-feral-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 103,
            name = "Feral - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAmZ2MzMzMmZ2M2GbzMzMPwMDAAAALBzmxwMjaGziZmZmlxMDAAAAAAGAAAAgmZZ2mZmBEYBMzAswgBAAwMbYA",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-103-feral-raids",
            classToken = "DRUID",
            specID = 103,
            name = "Feral - Raids",
            author = "Dvalin",
            rating = "A",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtlxyMbzYGzMDAAAALBzmhxMjaGziZmZGjZYAAAAAAMwAAAAIAYWmZpZbmlNwMDwiZwAAYmBAD",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-102-balance-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 102,
            name = "Balance - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmZhBMmZZmFzMzsMWmZZMzgNMAYssNzgxsNCMBAAAYhZmZGsZYMGAAmZgB",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-102-balance-raids",
            classToken = "DRUID",
            specID = 102,
            name = "Balance - Raids",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmhBDjZWGLzYGbjlZMmZGzCGAMALbjNMNzsMCAAAwmZmZmBbGYMDgZGAYA",
            verificationStatus = "legacy-unverified",
            notes = "Legacy Dvalin import preserved. Exact source post, patch, hero tree and leveling order have not been verified; the existing rating is not a verification grade.",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
    },
}
