local ADDON_NAME, NS = ...

NS.TALENT_BUILD_CUSTOM_ID = "CUSTOM"
NS.TALENT_BUILD_FILTER_ALL = "All"
NS.TALENT_BUILD_TYPE_BUILTIN = "Built-In"
NS.TALENT_BUILD_TYPE_USER = "User"
NS.TALENT_BUILD_TYPE_CUSTOM = "Custom"
NS.TALENT_BUILD_TYPES = {
    NS.TALENT_BUILD_TYPE_BUILTIN,
    NS.TALENT_BUILD_TYPE_USER,
    NS.TALENT_BUILD_TYPE_CUSTOM,
}
NS.TALENT_BUILD_RATINGS = { "S", "A", "B", "C", "D" }
NS.TALENT_BUILD_AUTO_APPLY_MODES = { "Auto-Apply", "Prompt Before Spending" }
NS.TALENT_BUILD_SOURCES = {
    NS.TALENT_BUILD_FILTER_ALL,
    "Icy Veins",
    "Noxxic",
    "Wowhead",
    "Discord",
    "Custom",
}
NS.TALENT_BUILD_SOURCE_URLS = {
    ["Icy Veins"] = "https://www.icy-veins.com/wow/news/single-button-assistant-and-assisted-highlight-design-intentions/",
    ["Noxxic"] = "https://www.noxxic.com/wow/",
    ["Wowhead"] = "https://www.wowhead.com/guide/classes",
    ["Discord"] = "",
    ["Custom"] = "",
}
NS.TALENT_BUILD_CATALOG = {
    version = 1,
    entries = {
        {
            id = "DISCORD-104-guardian-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmZml5BmZMWMLeg5BmZZZgZzMGNRzMziZmZmlxMAAAAAAMsNDYZbmBjZZAMFAAAYDz8ADYxMYwglNAzMAG",
            notes = "",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-104-guardian-raids",
            classToken = "DRUID",
            specID = 104,
            name = "Guardian - Raids",
            author = "Dvalin",
            rating = "A",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmZml5BmZM2MLj5BMLLDMbwoJamZWmZmZGjZAAAAAAYMbzA22mZwY2GATBAAA2MmZAWMDGMYZbAmZAM",
            notes = "",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-103-feral-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 103,
            name = "Feral - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAmZ2MzMzMmZ2M2GbzMzMPwMDAAAALBzmxwMjaGziZmZmlxMDAAAAAAGAAAAgmZZ2mZmBEYBMzAswgBAAwMbYA",
            notes = "",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-103-feral-raids",
            classToken = "DRUID",
            specID = 103,
            name = "Feral - Raids",
            author = "Dvalin",
            rating = "A",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtlxyMbzYGzMDAAAALBzmhxMjaGziZmZGjZYAAAAAAMwAAAAIAYWmZpZbmlNwMDwiZwAAYmBAD",
            notes = "",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-102-balance-dungeons-delves-open-world",
            classToken = "DRUID",
            specID = 102,
            name = "Balance - Dungeons, Delves & Open World",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmZhBMmZZmFzMzsMWmZZMzgNMAYssNzgxsNCMBAAAYhZmZGsZYMGAAmZgB",
            notes = "",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
        {
            id = "DISCORD-102-balance-raids",
            classToken = "DRUID",
            specID = 102,
            name = "Balance - Raids",
            author = "Dvalin",
            rating = "S",
            source = "Discord",
            catalogSource = "Discord",
            sourceURL = "",
            patch = "",
            importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmhBDjZWGLzYGbjlZMmZGzCGAMALbjNMNzsMCAAAwmZmZmBbGYMDgZGAYA",
            notes = "",
            category = "",
            buildType = NS.TALENT_BUILD_TYPE_BUILTIN,
        },
    },
}
