local ADDON_NAME, NS = ...

-- Generated by .scripts/generate-sba-priorities.py from reviewed source JSON.
-- Guide-informed acquisition priorities are project inferences, not DPS measurements.
-- Runtime restricts them to the matching patch, build and selected talent entries.
NS.TALENT_SBA_PRIORITIES = {
    [63] = {
        patch = "12.1",
        buildIDs = {
            ["BSBA-WH-SBA-COMPATIBLE-63-TARGETED-20260924"] = true,
        },
        spells = {
            [108853] = {
                name = "Fire Blast", priority = 100,
                reason = "Establish reliable Hot Streak generation.",
                sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/basics",
            },
            [11366] = {
                name = "Pyroblast", priority = 95,
                reason = "Add the main single-target Hot Streak spender.",
                sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/basics",
            },
            [190319] = {
                name = "Combustion", priority = 90,
                reason = "Keep the burst engine and activate Combustion manually.",
                sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/basics",
            },
            [1254851] = {
                name = "Flamestrike", priority = 85,
                reason = "Use the author-recommended targeted area spender.",
                sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/basics",
            },
            [383634] = {
                name = "Fiery Rush", priority = 80,
                reason = "Support Hot Streak generation inside the selected burst window.",
                sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/rotation-cooldowns-pve-dps",
            },
            [1257348] = {
                name = "Fired Up", priority = 75,
                reason = "Add the passive Apex synergy for Hot Streak and Combustion.",
                sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/rotation-cooldowns-pve-dps",
            },
        },
    },
    [102] = {
        patch = "12.1",
        buildIDs = {
            ["DISCORD-102-balance-dungeons-delves-open-world"] = true,
            ["DISCORD-102-balance-raids"] = true,
        },
        spells = {
            [1239669] = {
                name = "Eclipse", priority = 100,
                reason = "Establish the primary damage-buff engine.",
                sourceURL = "https://www.icy-veins.com/wow/balance-druid-pve-dps-easy-mode",
            },
            [202342] = {
                name = "Shooting Stars", priority = 95,
                reason = "Turn maintained DoTs into Astral Power and damage.",
                sourceURL = "https://static.icy-veins.com/json/midnight-talent-calculator/druid.json?v=44",
            },
            [93402] = {
                name = "Sunfire", priority = 90,
                reason = "Add the readily spread DoT foundation.",
                sourceURL = "https://www.icy-veins.com/wow/balance-druid-pve-dps-easy-mode",
            },
            [429523] = {
                name = "Lunar Calling", priority = 85,
                reason = "Establish the selected Lunar Eclipse specialization.",
                sourceURL = "https://www.icy-veins.com/wow/balance-druid-pve-dps-spec-builds-talents",
            },
            [450347] = {
                name = "Nature's Grace", priority = 80,
                reason = "Shorten the next builders after Eclipse or combat entry.",
                sourceURL = "https://static.icy-veins.com/json/midnight-talent-calculator/druid.json?v=44",
            },
            [279620] = {
                name = "Twin Moons", priority = 75,
                reason = "Spread Moonfire with fewer casts.",
                sourceURL = "https://www.icy-veins.com/wow/balance-druid-pve-dps-easy-mode",
            },
            [205636] = {
                name = "Force of Nature", priority = 70,
                reason = "Retain the chosen burst cooldown and its synergies.",
                sourceURL = "https://www.icy-veins.com/wow/balance-druid-pve-dps-easy-mode",
            },
            [1261564] = {
                name = "Ascendant Eclipses", priority = 65,
                reason = "Add Eclipse-linked instant builders and empowered spenders.",
                sourceURL = "https://www.icy-veins.com/wow/balance-druid-pve-dps-spec-builds-talents",
            },
        },
    },
    [103] = {
        patch = "12.1",
        buildIDs = {
            ["DISCORD-103-feral-dungeons-delves-open-world"] = true,
            ["DISCORD-103-feral-raids"] = true,
        },
        spells = {
            [106951] = {
                name = "Berserk", priority = 100,
                reason = "Keep the manual burst engine used before Convoke.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-easy-mode",
            },
            [285381] = {
                name = "Primal Wrath", priority = 95,
                reason = "First AoE swap: establish multi-target Rip.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-spec-builds-talents",
            },
            [391709] = {
                name = "Rampant Ferocity", priority = 90,
                reason = "Second AoE swap: spread Ferocious Bite damage.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-spec-builds-talents",
            },
            [391700] = {
                name = "Double-Clawed Rake", priority = 85,
                reason = "Third AoE swap: improve Rake coverage.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-spec-builds-talents",
            },
            [400320] = {
                name = "Circle of Life and Death", priority = 80,
                reason = "Speed bleed ticks for the selected Wildstalker engine.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-spec-builds-talents",
            },
            [155580] = {
                name = "Lunar Inspiration", priority = 75,
                reason = "Complete the selected Moonfire DoT package.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-easy-mode",
            },
            [421432] = {
                name = "Saber Jaws", priority = 70,
                reason = "Strengthen the selected single-target Bite package.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-spec-builds-talents",
            },
            [1263657] = {
                name = "Unseen Predator", priority = 65,
                reason = "Add the selected passive Ferocious Bite payoff.",
                sourceURL = "https://www.icy-veins.com/wow/feral-druid-pve-dps-spec-builds-talents",
            },
        },
    },
    [104] = {
        patch = "12.1",
        buildIDs = {
            ["DISCORD-104-guardian-dungeons-delves-open-world"] = true,
            ["DISCORD-104-guardian-raids"] = true,
        },
        spells = {
            [192081] = {
                name = "Ironfur", priority = 100,
                reason = "Secure active mitigation before damage refinements.",
                sourceURL = "https://www.icy-veins.com/wow/guardian-druid-pve-tank-easy-mode",
            },
            [22842] = {
                name = "Frenzied Regeneration", priority = 95,
                reason = "Keep the manual self-heal available.",
                sourceURL = "https://www.icy-veins.com/wow/guardian-druid-pve-tank-easy-mode",
            },
            [377210] = {
                name = "Ursoc's Fury", priority = 90,
                reason = "Convert the selected damage loop into absorb shields.",
                sourceURL = "https://www.icy-veins.com/wow/guardian-druid-pve-tank-spec-builds-talents",
            },
            [372945] = {
                name = "Reinvigoration", priority = 85,
                reason = "Strengthen the selected self-healing package.",
                sourceURL = "https://www.icy-veins.com/wow/guardian-druid-pve-tank-easy-mode",
            },
            [371905] = {
                name = "After the Wildfire", priority = 80,
                reason = "Add passive group healing from Rage spending.",
                sourceURL = "https://www.icy-veins.com/wow/guardian-druid-pve-tank-easy-mode",
            },
            [370586] = {
                name = "Elune's Favored", priority = 75,
                reason = "Turn selected Arcane damage into healing.",
                sourceURL = "https://static.icy-veins.com/json/midnight-talent-calculator/druid.json?v=44",
            },
            [204066] = {
                name = "Lunar Beam", priority = 70,
                reason = "Preserve the selected pull-opening damage and safety tool.",
                sourceURL = "https://www.icy-veins.com/wow/guardian-druid-pve-tank-spec-builds-talents",
            },
            [1269614] = {
                name = "Wild Guardian", priority = 65,
                reason = "Add passive attacks to Rage spending and core casts.",
                sourceURL = "https://static.icy-veins.com/json/midnight-talent-calculator/druid.json?v=44",
            },
        },
    },
    [250] = {
        patch = "12.1",
        buildIDs = {
            ["USER-SBA-250-LEVELING-20260924"] = true,
            ["USER-SBA-250-RAIDS-20260924"] = true,
        },
        spells = {
            [206930] = {
                name = "Heart Strike", priority = 100,
                reason = "Build Runic Power for Death Strike.",
                sourceURL = "https://www.icy-veins.com/wow/blood-death-knight-pve-tank-easy-mode",
            },
            [195182] = {
                name = "Marrowrend", priority = 95,
                reason = "Maintain Bone Shield for survival.",
                sourceURL = "https://www.icy-veins.com/wow/blood-death-knight-pve-tank-easy-mode",
            },
            [50842] = {
                name = "Blood Boil", priority = 90,
                reason = "Apply Blood Plague and use rotational charges.",
                sourceURL = "https://www.icy-veins.com/wow/blood-death-knight-pve-tank-easy-mode",
            },
            [49028] = {
                name = "Dancing Rune Weapon", priority = 85,
                reason = "Support damage, parry, and resource generation.",
                sourceURL = "https://www.icy-veins.com/wow/blood-death-knight-pve-tank-easy-mode",
            },
            [55233] = {
                name = "Vampiric Blood", priority = 80,
                reason = "Keep a major survival cooldown available.",
                sourceURL = "https://www.icy-veins.com/wow/blood-death-knight-pve-tank-easy-mode",
            },
            [273946] = {
                name = "Hemostasis", priority = 75,
                reason = "Strengthen Death Strike through the core rotation.",
                sourceURL = "https://www.icy-veins.com/wow/blood-death-knight-pve-tank-easy-mode",
            },
        },
    },
    [251] = {
        patch = "12.1",
        buildIDs = {
            ["WH-SBA-COMPATIBLE-251-20260812"] = true,
        },
        spells = {
            [51128] = {
                name = "Killing Machine", priority = 100,
                reason = "Build the proc engine before its supporting talents.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/basics",
            },
            [49020] = {
                name = "Obliterate", priority = 95,
                reason = "Add the principal Killing Machine spender.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/basics",
            },
            [49184] = {
                name = "Howling Blast", priority = 90,
                reason = "Complete the Rime spending part of the core rotation.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/basics",
            },
            [49143] = {
                name = "Frost Strike", priority = 85,
                reason = "Complete the core Runic Power spending loop.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/basics",
            },
            [51271] = {
                name = "Pillar of Frost", priority = 80,
                reason = "Establish the burst window used by downstream synergies.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/rotation-cooldowns-pve-dps",
            },
            [281238] = {
                name = "Obliteration", priority = 75,
                reason = "Strengthen the established Pillar and Killing Machine engine.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/rotation-cooldowns-pve-dps",
            },
            [377226] = {
                name = "Frozen Dominion", priority = 70,
                reason = "Add passive Remorseless Winter integration to the selected build.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/rotation-cooldowns-pve-dps",
            },
            [279302] = {
                name = "Frostwyrm's Fury", priority = 65,
                reason = "Retain the selected burst cooldown and its Apex synergy.",
                sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/rotation-cooldowns-pve-dps",
            },
        },
    },
    [253] = {
        patch = "12.1",
        buildIDs = {
            ["WH-SBA-COMPATIBLE-253-20260812"] = true,
        },
        spells = {
            [19574] = {
                name = "Bestial Wrath", priority = 100,
                reason = "Establish the main pet damage cooldown.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/basics",
            },
            [34026] = {
                name = "Kill Command", priority = 95,
                reason = "Add the principal pet attack before its supporting synergies.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/basics",
            },
            [217200] = {
                name = "Barbed Shot", priority = 90,
                reason = "Complete the core charge-based pet rotation.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/basics",
            },
            [1264359] = {
                name = "Wild Thrash", priority = 85,
                reason = "Add the trigger for the selected pet cleave engine.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/rotation-cooldowns-pve-dps",
            },
            [115939] = {
                name = "Beast Cleave", priority = 80,
                reason = "Enable pet cleave once its selected trigger is available.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/rotation-cooldowns-pve-dps",
            },
            [1273043] = {
                name = "Nature's Ally", priority = 75,
                reason = "Add passive pet damage that supports the core Kill Command loop.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/rotation-cooldowns-pve-dps",
            },
            [1272099] = {
                name = "Bloodshed", priority = 70,
                reason = "Strengthen the selected Bestial Wrath pet damage package.",
                sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/rotation-cooldowns-pve-dps",
            },
        },
    },
    [258] = {
        patch = "12.1",
        buildIDs = {
            ["WH-SBA-COMPATIBLE-258-20260812"] = true,
        },
        spells = {
            [335467] = {
                name = "Shadow Word: Madness", priority = 100,
                reason = "Selected Insanity spender; score inferred from Wowhead's rotation.",
                sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/the-war-within-guide",
            },
            [199484] = {
                name = "Psychic Link", priority = 95,
                reason = "Selected passive that spreads direct damage to Vampiric Touch targets.",
                sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/the-war-within-guide",
            },
            [450405] = {
                name = "Void Blast", priority = 90,
                reason = "Selected Voidweaver payoff for the guide's Void Torrent interaction.",
                sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/the-war-within-guide",
            },
            [375888] = {
                name = "Shadowy Insight", priority = 85,
                reason = "Selected proc talent named in Wowhead's Shadow priority list.",
                sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/the-war-within-guide",
            },
            [238558] = {
                name = "Misery", priority = 80,
                reason = "Selected DoT synergy inferred from Wowhead's maintain-your-DoTs guidance.",
                sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/the-war-within-guide",
            },
        },
    },
    [268] = {
        patch = "12.1",
        buildIDs = {
            ["WH-SBA-COMPATIBLE-268-20260812"] = true,
        },
        spells = {
            [121253] = {
                name = "Keg Smash", priority = 100,
                reason = "Selected core loop talent that grants Shuffle and reduces Brew cooldowns.",
                sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/abilities-talents-pve-tank",
            },
            [119582] = {
                name = "Purifying Brew", priority = 95,
                reason = "Selected core defensive talent that preserves Brewmaster's survival base.",
                sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/abilities-talents-pve-tank",
            },
            [383695] = {
                name = "Improved Blackout Kick", priority = 90,
                reason = "Selected Blackout Kick upgrade scored from the guide's core-loop priority.",
                sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/tank-leveling-tips",
            },
            [1241059] = {
                name = "Celestial Infusion", priority = 85,
                reason = "Selected Master of Harmony trigger for stored-vitality throughput.",
                sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/the-war-within-guide",
            },
            [196736] = {
                name = "Blackout Combo", priority = 75,
                reason = "Selected rotation passive that Wowhead says is important to use well.",
                sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/rotation-cooldowns-pve-tank",
            },
            [325153] = {
                name = "Exploding Keg", priority = 70,
                reason = "Selected burst/threat cooldown with a short melee-damage reduction.",
                sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/tank-leveling-tips",
            },
        },
    },
    [577] = {
        patch = "12.1",
        buildIDs = {
            ["ICY-577-sba-fel-scarred-raid"] = true,
            ["ICY-577-sba-fel-scarred-dungeon"] = true,
        },
        spells = {
            [198013] = {
                name = "Eye Beam", priority = 100,
                reason = "Start the Eye Beam/Demonic burst engine.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
            [213410] = {
                name = "Demonic", priority = 95,
                reason = "Make Eye Beam trigger demon form.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
            [452402] = {
                name = "Demonsurge", priority = 92,
                reason = "Add Fel-Scarred's empowered-cast damage engine.",
                sourceURL = "https://static.icy-veins.com/json/midnight-talent-calculator/demon_hunter.json?v=44",
            },
            [258887] = {
                name = "Cycle of Hatred", priority = 90,
                reason = "Build the recurring 20-second Eye Beam cycle.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
            [388116] = {
                name = "Shattered Destiny", priority = 85,
                reason = "Extend demon form through Fury spending.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
            [427775] = {
                name = "A Fire Inside", priority = 80,
                reason = "Strengthen the selected Immolation Aura package.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
            [388107] = {
                name = "Ragefire", priority = 75,
                reason = "Turn Immolation Aura critical damage into an AoE burst.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
            [1270898] = {
                name = "Eternal Hunt", priority = 70,
                reason = "Keep The Hunt's Eye Beam synergy when selected.",
                sourceURL = "https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-spec-builds-talents",
            },
        },
    },
    [1480] = {
        patch = "12.1",
        buildIDs = {
            ["ICY-1480-sba-annihilator-single-target"] = true,
            ["ICY-1480-sba-annihilator-aoe"] = true,
        },
        spells = {
            [471306] = {
                name = "Void Metamorphosis", priority = 100,
                reason = "Establish Annihilator's central transformation engine.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
            [473728] = {
                name = "Void Ray", priority = 95,
                reason = "Add the Fury channel and selected Reap synergies.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
            [1253304] = {
                name = "Voidfall", priority = 92,
                reason = "Start Annihilator's Consume-to-Reap meteor engine.",
                sourceURL = "https://static.icy-veins.com/json/midnight-talent-calculator/demon_hunter.json?v=44",
            },
            [1221167] = {
                name = "Collapsing Star", priority = 90,
                reason = "Keep the payoff for extended metamorphosis windows.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
            [1242492] = {
                name = "Emptiness", priority = 85,
                reason = "Use ramping Haste to extend metamorphosis.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
            [1246555] = {
                name = "Tempered Soul", priority = 80,
                reason = "Smooth Soul Immolation with its extra charge.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
            [1238739] = {
                name = "Soulshaper", priority = 75,
                reason = "Strengthen Reap's Soul Fragment scaling.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
            [1242486] = {
                name = "Midnight", priority = 70,
                reason = "Support the selected Collapsing Star payoff.",
                sourceURL = "https://www.icy-veins.com/wow/devourer-demon-hunter-pve-dps-spec-builds-talents",
            },
        },
    },
}
