// Copy this file with the Workboard to track another project. The interface
// reads this object directly, so it also works from file:// without a server.
window.WORKBOARD_PROJECT = {
  key: "bettersba",
  name: "BetterSBA",
  subtitle: "Retail Addon · Development Workboard",
  updated: "2026-09-25",
  defaultTheme: "alliance",
  spotlight: "F02",
  repository: "https://github.com/zero-wow/BetterSBA",
  activity: [
    { date: "Sep 25", id: "F01", text: "Removed doubled switch and heading text layers; regenerated comic lettering and checked header gutters locally. In-game check remains." },
    { date: "Sep 25", id: "A02", text: "Per-spec talent routes verified across specialization switches." },
    { date: "Sep 25", id: "F07", text: "Overlapping Studio navigation lettering removed; in-game check remains." }
  ],
  items: [
    { id: "A01", lane: "Add", title: "Middle-Click Settings Access", priority: "High", state: "Verify", summary: "Open the saved configuration panel from the live button.", doneWhen: "Middle-click toggles settings and never runs the SBA macro or cast press visual.", evidence: "Implemented in GUI/MainButton.lua; startup mock passes. In-game check remains." },
    { id: "A02", lane: "Add", title: "Per-Spec Route Defaults", priority: "High", state: "Done", summary: "Remember a preferred SBA talent route for each specialization.", doneWhen: "Changing specs restores that spec's route without changing another spec's choice.", evidence: "Character-local state is keyed by spec in TalentLeveling.lua. The talent-leveling test switches from Arcane to Fire and back, confirming both routes remain independent." },
    { id: "A03", lane: "Add", title: "Talent Source Freshness Labels", priority: "High", state: "Backlog", summary: "Show patch, season, source, and last review date beside each build.", doneWhen: "Every bundled route clearly distinguishes verified, adapted, and user-supplied data." },
    { id: "A04", lane: "Add", title: "Talent Spend History", priority: "Medium", state: "Backlog", summary: "Record recent auto-spend steps and why each rank was chosen.", doneWhen: "The Talent page shows a bounded per-character history with build and level context." },
    { id: "A05", lane: "Add", title: "First-Run Route Setup", priority: "Medium", state: "Backlog", summary: "Guide a new character through build selection and auto-spend in one short flow.", doneWhen: "A fresh character can choose a route and understand the next point without reading a settings wall." },
    { id: "A06", lane: "Add", title: "Profile Export And Import", priority: "Medium", state: "Backlog", summary: "Share settings through a versioned text export.", doneWhen: "Import previews changed values and rejects malformed or incompatible data safely." },
    { id: "A07", lane: "Add", title: "Motion Audition Gallery", priority: "Medium", state: "Backlog", summary: "Preview every motion preset side by side before choosing one.", doneWhen: "Pulse, Echo, Sweep, Sheen, Snap, and Orbit each have a reliable one-shot preview." },
    { id: "A08", lane: "Add", title: "Reminder Placement Presets", priority: "Low", state: "Backlog", summary: "Place manual cooldown reminders with named anchors around the live button.", doneWhen: "Presets stay readable with both queue positions and at supported scales." },
    { id: "A09", lane: "Add", title: "Copy Diagnostics Report", priority: "Medium", state: "Backlog", summary: "Collect addon version, client build, spec, route, and recent errors for support.", doneWhen: "One action produces a short report without character-private data or secrets." },
    { id: "A10", lane: "Add", title: "Build Favorites", priority: "Low", state: "Backlog", summary: "Pin frequently used talent routes in the library.", doneWhen: "Favorites persist by profile and remain distinct from the active leveling target." },

    { id: "F01", lane: "Fix", title: "Verify Compact Labels In WoW", priority: "High", state: "Verify", summary: "Confirm illustrated headings and On/Off values render at real game scale.", doneWhen: "No blank or doubled labels at minimum, default, or enlarged UI scale on both factions.", evidence: "Fixed labels now hide native glyphs while their raster art remains visible; On/Off art was redrawn as single-layer Kalam lettering. Studio mock and faction previews pass; in-game visual verification remains." },
    { id: "F02", lane: "Fix", title: "Resolve Invalid Talent Rank Reports", priority: "Critical", state: "Next", summary: "Trace the remaining purchased-rank warning, including node 99822.", doneWhen: "Valid partial leveling builds decode without the warning; invalid data names the exact cause.", evidence: "Local fixtures defer node 99822 when its hero entries are locked or missing. The reported live-tree rank mismatch still needs its actual import rank and node capacity checked before changing the decoder." },
    { id: "F03", lane: "Fix", title: "Recover Rejected Talent Commits", priority: "Critical", state: "Verify", summary: "Retry safely after WoW rejects a talent change while auto-spend is already enabled.", doneWhen: "A failed commit cannot leave the route stuck until the user toggles auto-spend.", evidence: "TalentLeveling.lua rolls back only the staged rank it owns, retries once, then attempts one guarded rebuild. Tests cover rejection, combat delay, cancellation, and recovery limits; an in-game rejection has not been verified." },
    { id: "F04", lane: "Fix", title: "Keep Auto-Spend State In Sync", priority: "High", state: "Backlog", summary: "Reconcile checkbox, route summary, death state, and reload status.", doneWhen: "All surfaces show one state and resume correctly after death, resurrection, and reload." },
    { id: "F05", lane: "Fix", title: "Make Sweep Read Clearly", priority: "High", state: "Backlog", summary: "Repair the Sweep feedback so it is visible at common button sizes.", doneWhen: "The sweep is visible once per trigger without obscuring the spell icon." },
    { id: "F06", lane: "Fix", title: "Make Orbit Read Clearly", priority: "High", state: "Backlog", summary: "Repair the Orbit feedback path and timing.", doneWhen: "The light completes a visible orbit in preview and during live casts." },
    { id: "F07", lane: "Fix", title: "Eliminate Studio Clipping", priority: "High", state: "Next", summary: "Audit controls, art, headings, and dialogs across window sizes.", doneWhen: "No content overlaps, clips, or touches a divider at minimum size or after resizing.", evidence: "Navigation collision was removed earlier. Every group heading now clears the ribbon's slanted edge and its divider in the Studio mock; broader in-game page and resize audit remains." },
    { id: "F08", lane: "Fix", title: "Validate Secure Input In Combat", priority: "High", state: "Backlog", summary: "Check left-click, keybind, drag, and middle-click behavior against combat lockdown.", doneWhen: "No taint or blocked casts; middle-click opens settings without casting." },
    { id: "F09", lane: "Fix", title: "Refresh Settings After Profile Changes", priority: "Medium", state: "Backlog", summary: "Remove stale values after switch, copy, rename, and reset actions.", doneWhen: "Every visible control and summary reflects the active profile immediately." },
    { id: "F10", lane: "Fix", title: "Recheck LazyGrip Build Imports", priority: "High", state: "Backlog", summary: "Validate current-season individual-page imports and SBA labels.", doneWhen: "Every listed LazyGrip route has correct spec identity, provenance, and import behavior." },

    { id: "R01", lane: "Reimagine", title: "One Coherent Settings Map", priority: "High", state: "Backlog", summary: "Reduce the split between Classic and Studio without hiding advanced controls.", doneWhen: "Every existing option has a clear home and an obvious path from the main panel." },
    { id: "R02", lane: "Reimagine", title: "Talent Route As A Journey", priority: "High", state: "Backlog", summary: "Present current build, next legal point, and safety state as one flow.", doneWhen: "A leveling player understands what happens next in one glance." },
    { id: "R03", lane: "Reimagine", title: "Spec-First Build Library", priority: "High", state: "Backlog", summary: "Organize routes around class, spec, content, and SBA confidence.", doneWhen: "Players can find a suitable route without scanning a dense generic table." },
    { id: "R04", lane: "Reimagine", title: "Motion Storyboard", priority: "Medium", state: "Backlog", summary: "Turn motion setup into a visual sequence with timing and intensity.", doneWhen: "A preview explains each phase and the controls map directly to what moves." },
    { id: "R05", lane: "Reimagine", title: "Talent Alert Decisions", priority: "High", state: "Backlog", summary: "Replace long warning blocks with cause, safe action, and expected result.", doneWhen: "A mismatch or failed commit presents one clear next step without jargon." },
    { id: "R06", lane: "Reimagine", title: "Button And Queue Canvas", priority: "Medium", state: "Backlog", summary: "Tune placement against a live-scale visual preview.", doneWhen: "Resize and position controls show their effect before closing settings." },
    { id: "R07", lane: "Reimagine", title: "Profiles As Compare And Copy", priority: "Medium", state: "Backlog", summary: "Make profile differences inspectable before copying or resetting.", doneWhen: "Players see what will change before a destructive profile action." },
    { id: "R08", lane: "Reimagine", title: "Assistance Status Hub", priority: "Medium", state: "Backlog", summary: "Explain what Blizzard SBA recommends and what BetterSBA adds.", doneWhen: "The panel separates active assistance, pauses, manual reminders, and automation state." },
    { id: "R09", lane: "Reimagine", title: "Shared Faction Art System", priority: "Medium", state: "Backlog", summary: "Give Alliance and Horde one consistent component grammar with distinct palettes.", doneWhen: "Every page and subpanel has complete faction art without theme leaks." },
    { id: "R10", lane: "Reimagine", title: "Readable Motion Modes", priority: "Low", state: "Backlog", summary: "Offer an intentional reduced-motion and higher-contrast experience.", doneWhen: "Information survives when effects are reduced and remains clear over both faction backgrounds." },

    { id: "P01", lane: "Polish", title: "Title Case Audit", priority: "Medium", state: "Backlog", summary: "Apply the agreed casing to labels, buttons, and section names.", doneWhen: "UI labels use Title Case while sentences remain normal prose." },
    { id: "P02", lane: "Polish", title: "Illustrated Button Lettering", priority: "High", state: "Verify", summary: "Use exact comic lettering images on fixed faction-art buttons.", doneWhen: "No blank, doubled, or clipped action labels at supported scales; hover and press art still work.", evidence: "100 power-of-two TGA lettering assets now use one ink layer, including all dynamic particle headings; Alliance and Horde previews and the local Studio mock pass. In-game rendering awaits verification." },
    { id: "P03", lane: "Polish", title: "Tighten Panel Spacing", priority: "High", state: "Backlog", summary: "Remove excess padding around headers, rows, and section transitions.", doneWhen: "Pages feel dense but never crowded at the smallest supported window." },
    { id: "P04", lane: "Polish", title: "Align Dividers And Gutters", priority: "Medium", state: "Backlog", summary: "Give art, text, and controls consistent edge clearances.", doneWhen: "Nothing sits on a border or divider across disclosed and scrolled states." },
    { id: "P05", lane: "Polish", title: "Refine Button Motion", priority: "Medium", state: "Backlog", summary: "Unify hover glow, click response, and gleam without oversized flourishes.", doneWhen: "All clickable controls share deliberate motion that fits their size." },
    { id: "P06", lane: "Polish", title: "Finish Pause Treatment", priority: "Medium", state: "Backlog", summary: "Keep the icon visible under a restrained pause mark and a plain reason label.", doneWhen: "Paused state is unmistakable without a distracting badge or glow block." },
    { id: "P07", lane: "Polish", title: "Resize And Edge Pass", priority: "High", state: "Backlog", summary: "Inspect drag-resize and UI-scale behavior on all Studio pages.", doneWhen: "Window edges, portraits, controls, and popups stay aligned from minimum to maximum." },
    { id: "P08", lane: "Polish", title: "Interaction Hints", priority: "Low", state: "Backlog", summary: "Show middle-click, Ctrl+wheel, and drag hints where they help.", doneWhen: "Hints are discoverable without covering the live button or adding constant UI noise." },
    { id: "P09", lane: "Polish", title: "Faction Contrast Pass", priority: "Medium", state: "Backlog", summary: "Balance Alliance blue and gold with Horde undercity green, purple, and red.", doneWhen: "Text and controls remain readable over both comic paper backgrounds." },
    { id: "P10", lane: "Polish", title: "Refresh Screenshots And Docs", priority: "Low", state: "Backlog", summary: "Keep instructions and screenshots aligned with the actual panel.", doneWhen: "README, tooltips, and examples show the current UI and current font choices." }
  ]
};
