"""Build the bundled priority table from reviewed, source-linked research JSON.

Run from any directory. This does not fetch sources, infer new scores, or change
talent imports. Review the source JSON before regenerating for a new patch.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sources = sorted((ROOT / "docs").glob("sba-priorities-*.json"))
profiles = {}
for path in sources:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    for target in data.get("targets", data.get("specs", [])):
        spec = target["specID"]
        assert spec not in profiles, f"Duplicate spec {spec}"
        patch = target.get("patch", target.get("sourcePatch", data.get("patch")))
        patch = ".".join(patch.split(".")[:2])
        builds = target.get("buildIDs", [target.get("targetBuildID")])
        assert builds and all(builds), f"Missing target scope for {spec}"
        rules = {}
        for rule in target["priorities"]:
            spell = rule["spellID"]
            name = rule.get("name", rule.get("talentName", rule.get("englishName")))
            reason = rule.get("reason", rule.get("shortReason"))
            assert name and reason and len(reason) <= 140, f"Missing/long UI reason for {spec}:{spell}"
            assert rule["evidenceType"] == "inference", "Acquisition weights must be labelled inference"
            assert spell not in rules and 0 < rule["priority"] <= 100, f"Bad priority {spec}:{spell}"
            assert rule["sourceURL"].startswith("https://"), f"Missing source {spec}:{spell}"
            rules[spell] = {"name": name, "priority": rule["priority"], "reason": reason, "sourceURL": rule["sourceURL"]}
        assert rules, f"Empty guidance for {spec}"
        profiles[spec] = (patch, builds, rules)

def quote(value):
    return json.dumps(value, ensure_ascii=False)

lines = [
    "local ADDON_NAME, NS = ...", "",
    "-- Generated by .scripts/generate-sba-priorities.py from reviewed source JSON.",
    "-- Guide-informed acquisition priorities are project inferences, not DPS measurements.",
    "-- Runtime restricts them to the matching patch, build and selected talent entries.",
    "NS.TALENT_SBA_PRIORITIES = {",
]
count = 0
for spec, (patch, builds, rules) in sorted(profiles.items()):
    lines += [f"    [{spec}] = {{", f"        patch = {quote(patch)},", "        buildIDs = {"]
    lines += [f"            [{quote(build)}] = true," for build in builds]
    lines += ["        },", "        spells = {"]
    for spell, rule in sorted(rules.items(), key=lambda item: (-item[1]["priority"], item[0])):
        lines += [f"            [{spell}] = {{", f"                name = {quote(rule['name'])}, priority = {rule['priority']},",
                  f"                reason = {quote(rule['reason'])},", f"                sourceURL = {quote(rule['sourceURL'])},", "            },"]
        count += 1
    lines += ["        },", "    },"]
lines += ["}", ""]
assert profiles, "No reviewed sources found"
(ROOT / "Core" / "TalentPriorityData.lua").write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {count} priority rules for {len(profiles)} specs")
